name: Supabase DB Push (no DB_URL)

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase login
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Push migrations to remote
        run: supabase db push --project-ref "$SUPABASE_PROJECT_REF" --yes --debug

      - name: Summary
        run: echo "Migrations pushed to $SUPABASE_PROJECT_REF"